# Generated by Django 3.2.6 on 2022-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_baserowuser_database_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserowuser',
            name='database_id',
        ),
        migrations.AddField(
            model_name='baserowuser',
            name='dishes_table_id',
            field=models.IntegerField(default=0, null=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baserowuser',
            name='ingredients_table_id',
            field=models.IntegerField(default=0, null=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baserowuser',
            name='materials_table_id',
            field=models.IntegerField(default=0, null=None),
            preserve_default=False,
        ),
    ]
