# Generated by Django 3.2.6 on 2022-01-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220109_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserowuser',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
