# Generated by Django 3.2.6 on 2022-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_baserowuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baserowuser',
            old_name='mail',
            new_name='baserow_mail',
        ),
        migrations.RemoveField(
            model_name='baserowuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='baserowuser',
            name='recipebook_db_name',
        ),
        migrations.AddField(
            model_name='baserowuser',
            name='dishes_tableid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
