# Generated by Django 3.2.6 on 2022-01-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220111_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baserowuser',
            old_name='dishes_tableid',
            new_name='dishes_table_id',
        ),
    ]
