# Generated by Django 3.2.6 on 2022-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserowuser',
            name='database_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
