# Generated by Django 3.2.6 on 2022-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220109_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserowuser',
            name='dishes_table_id',
        ),
        migrations.RemoveField(
            model_name='baserowuser',
            name='ingredients_table_id',
        ),
        migrations.RemoveField(
            model_name='baserowuser',
            name='materials_table_id',
        ),
        migrations.AddField(
            model_name='baserowuser',
            name='recipebook_db_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
